[package]
name = "waveform"
version = "0.1.0"
edition = "2021"

[lib]
name = "waveform"
crate-type = ["cdylib"]

[dependencies]
ffmpeg-next = "*"
tempfile = "*"
base64 = "*"
pyo3 = { version = "*", features = ["extension-module"] }
